services:
  - type: web
    name: urvi-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: your-database-url-here
    branch: main
    autoDeploy: true
